"""M00-02 도메인 스키마 + 공통 오류. 모든 모듈 간 데이터는 이 스키마로만 주고받는다 (C-02)."""

from myfinsight.schemas.enums import (
    DataStatus,
    IndexCode,
    RiskType,
    SelectionRule,
    StepStatus,
    WeightingRule,
)
from myfinsight.schemas.errors import (
    BacktestError,
    ConfigError,
    ConsistencyError,
    DataQualityError,
    DataSourceError,
    InputError,
    MyFinSightError,
    RepositoryError,
    SpecValidationError,
    StrategyError,
    WeightValidationError,
)
from myfinsight.schemas.market import (
    DataQualityReport,
    FxRate,
    IndexConstituent,
    PriceBar,
    PriceMeta,
    RawPriceBatch,
    TickerQuality,
    UniverseResult,
)
from myfinsight.schemas.profile import ProfileConstraints, UserProfile
from myfinsight.schemas.report import AllocationRow, EvidenceItem, Report, ReportData
from myfinsight.schemas.results import (
    METRIC_MOMENTUM,
    METRIC_VOLATILITY,
    BacktestResult,
    CalcConditions,
    MetricsBundle,
    PerformanceMetrics,
    RebalanceRecord,
    TickerSignal,
    ValidationIssue,
    ValidationResult,
    WeightSet,
)
from myfinsight.schemas.runlog import StepRecord
from myfinsight.schemas.spec import (
    ConstraintSpec,
    SelectionSpec,
    StrategySpec,
    UniverseSpec,
    WeightingSpec,
)

__all__ = [
    "METRIC_MOMENTUM",
    "METRIC_VOLATILITY",
    "AllocationRow",
    "BacktestError",
    "BacktestResult",
    "CalcConditions",
    "ConfigError",
    "ConsistencyError",
    "ConstraintSpec",
    "DataQualityError",
    "DataQualityReport",
    "DataSourceError",
    "DataStatus",
    "EvidenceItem",
    "FxRate",
    "IndexCode",
    "IndexConstituent",
    "InputError",
    "MetricsBundle",
    "MyFinSightError",
    "PerformanceMetrics",
    "PriceBar",
    "PriceMeta",
    "ProfileConstraints",
    "RawPriceBatch",
    "RebalanceRecord",
    "Report",
    "ReportData",
    "RepositoryError",
    "RiskType",
    "SelectionRule",
    "SelectionSpec",
    "SpecValidationError",
    "StepRecord",
    "StepStatus",
    "StrategyError",
    "StrategySpec",
    "TickerQuality",
    "TickerSignal",
    "UniverseResult",
    "UniverseSpec",
    "UserProfile",
    "ValidationIssue",
    "ValidationResult",
    "WeightSet",
    "WeightValidationError",
    "WeightingRule",
    "WeightingSpec",
]
